### PR TITLE
Amazing new feature

### PR DESCRIPTION
**Pull request by natanfudge**
Amazing. Not made by bot

### CODE REVIEW

**Comment by shedaniel** [comment]
has your bot just been deleting stuff

**Comment by natanfudge** [comment]
no i'm just deleting them because it won't let me make a new one when there's one already open

**Comment by natanfudge** [comment]
right now I get errors when parsing the result json

**Comment by shedaniel** [comment]
very sad

**Comment by shedaniel** [comment]
good luck on this

**Comment by natanfudge** [comment]
it's because rust tooling is bad

**Comment by natanfudge** [comment]
look at what I need to do to fix this 
image

**Pull request closed without merging**
